name: Deploy DHI to Production

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: Production
    env:
      NEXT_PUBLIC_DIRECTUS_PROTOCOL: ${{ vars.DIRECTUS_PROTOCOL }}
      NEXT_PUBLIC_DIRECTUS_HOST: ${{ vars.DIRECTUS_HOST }}
      NEXT_PUBLIC_DIRECTUS_BASE_URL: ${{ vars.DIRECTUS_PROTOCOL }}://${{ vars.DIRECTUS_HOST }}
      NEXT_PUBLIC_DIRECTUS_GRAPHQL: ${{ vars.DIRECTUS_PROTOCOL }}://${{ vars.DIRECTUS_HOST }}/graphql
      NEXT_PUBLIC_DIRECTUS_GRAPHQL_SYSTEM: ${{ vars.DIRECTUS_PROTOCOL }}://${{ vars.DIRECTUS_HOST }}/graphql/system
      NEXT_PUBLIC_API_BASE_URL: ${{ vars.API_BASE_URL }}
      NEXT_PUBLIC_COOKIE_EXPIRE_DAYS: ${{ vars.COOKIE_EXPIRE_DAYS }}
    steps:
      - name: 🚚 SSH to server - 🔨 Build Project
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: app.dhicolombia.net
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script_stop: true
          envs: NEXT_PUBLIC_DIRECTUS_PROTOCOL, NEXT_PUBLIC_DIRECTUS_HOST, NEXT_PUBLIC_DIRECTUS_BASE_URL, NEXT_PUBLIC_DIRECTUS_GRAPHQL, NEXT_PUBLIC_DIRECTUS_GRAPHQL_SYSTEM, NEXT_PUBLIC_API_BASE_URL, NEXT_PUBLIC_COOKIE_EXPIRE_DAYS
          script: |
            cd /home/dhi/dhi_app/
            git pull
            npm install -g n
            n install lts
            n lts
            npm run production-build
            sudo systemctl restart pm2-root
            sudo systemctl restart nginx
